from pathlib import Path
import json,csv,collections,hashlib,subprocess,datetime
ROOT=Path.cwd();P=ROOT/'docs/remediation/2026-10-01-rdpms';S=Path(__file__).resolve().parent;R=P/'execution/RP19/RP19-T04/runs'/S.name;E=R/'evidence'
def save(p,d):p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
state=json.loads((P/'IMPLEMENTATION_STATE.json').read_text());graph=json.loads((P/'TASK_GRAPH.json').read_text());g={t['id']:t for t in graph['tasks']};matrix=list(csv.DictReader((P/'ACCEPTANCE_MATRIX.csv').open(encoding='utf-8-sig')));cases={r['case_id']:r for r in matrix};findings=json.loads((P/'FINDING_TO_PACKAGE.json').read_text())['records'];records=[]
assert len(state['tasks'])==54 and len(matrix)==306 and len(findings)==33
for f in findings:
 ids=f.get('primaryTaskRefs',[]);trs=[{'taskId':t,'implementation':state['tasks'][t]['implementation'],'validation':state['tasks'][t]['validation'],'release':state['tasks'][t].get('release','NOT_EVALUATED'),'latestRun':state['tasks'][t].get('latestRun'),'evidence':state['tasks'][t].get('evidence',[])} for t in ids]
 associated=[{'caseId':c['case_id'],'result':c['result'],'evidence':c['evidence_ref'],'evidenceLevel':c['evidence_level']} for c in matrix if c['finding_id']==f['id']]
 records.append({'findingId':f['id'],'severity':f['severity'],'candidateOnly':f.get('candidateOnly',False),'frozenDisposition':f['disposition'],'primaryPackage':f['primaryPackage'],'primaryTaskStates':trs,'caseResults':associated,'localRepairStatus':'PENDING_EXTERNAL_COORDINATION_ARBITRATION' if f.get('candidateOnly') else 'LOCAL_SCOPED_EVIDENCE_AVAILABLE_TARGET_OPEN' if any(t['implementation']=='COMPLETE' for t in trs) else 'IMPLEMENTATION_AND_DATA_INPUT_PENDING','fixAcceptance':'NOT_CLOSED','target':'NOT_RUN','release':'NOT_EVALUATED','residualRiskAcceptance':'NONE_INVENTED','historicalRef':f.get('evidenceRef'),'latestLocalRef':f.get('latestExecutionEvidence')})
confirmed=[r for r in records if not r['candidateOnly']];assert len(confirmed)==32 and collections.Counter(r['severity'] for r in confirmed)=={'P1':16,'P2':16}
implementation=dict(collections.Counter(t['implementation'] for t in state['tasks'].values()));validation=dict(collections.Counter(t['validation'] for t in state['tasks'].values()));acceptance=dict(collections.Counter(r['result'] for r in matrix));remaining=[]
materials={'RP10-T01':'S03-OI-09: supported deployed client/producer versions, POST/PUT/sync revision carrying behavior, legacy queued drafts/send history and upgrade/retirement window. Static currentcandidate matrix alone cannot establish deployed clients.','RP15-T01':'S04-OI-01: data-owner-approved minimized read-only historical snapshot/anomaly inventory with stable IDs/counts/reference fields and provenance. No production/shared data access was authorized.','RP15-T02':'After RP15-T01 actual anomaly classification, approved non-destructive repair mapping/quarantine and exact FK/unique scope; synthetic invented backfill does not repair historical rows.','RP15-T03':'After RP15-T02 actual verified mapping and rollback copies, target-safe migration validation/rollback, no current database destructive DDL.','RP01-T03':'OPTIONAL inactive custom-role binding extension; current standard seed role protection complete. Do not expand scope from blanket local repair authorization.','RP05-T03':'OPTIONAL inactive general DAG/live/deletion semantics extension; current parent guards/delta commands complete. Do not turn enhancement into required defect remediation.'}
for tid,t in state['tasks'].items():
 if t['implementation']=='COMPLETE':continue
 remaining.append({'taskId':tid,'activation':g[tid]['activation'],'implementation':t['implementation'],'validation':t['validation'],'implementationDependencies':g[tid].get('implementationDependencies',[]),'acceptanceDependencies':g[tid].get('acceptanceDependencies',[]),'conditionalGates':g[tid].get('gateRequirements',[]),'minimumMaterialOrCondition':materials.get(tid,'Current documentary task in progress, completion after this final account'),'needsRepeatedLocalAuthorization':False,'optional':tid in ['RP01-T03','RP05-T03']})
d={'asOf':datetime.datetime.now().astimezone().isoformat(),'head':subprocess.check_output(['git','rev-parse','HEAD'],text=True).strip(),'54TaskImplementation':implementation,'54TaskValidation':validation,'306CaseResults':acceptance,'recordCount':33,'confirmedSupportedCount':32,'confirmedSeverities':{'P1':16,'P2':16},'candidateCount':1,'programmeClosure':'NOT_CLOSED','targetRelease':'NOT_EVALUATED','records':records,'remainingTasks':remaining,'notes':['Implementation COMPLETE means scoped delivery; ENV_BLOCKED/NOT_RUN are not passing acceptance.','31 frozen audit open items and all old audit evidence untouched; no new global FIX_ACCEPTED/RISK_ACCEPTED/deployment claim.','Candidate R12-N01 remainsPENDING; local commonpoint enhancement is not original external coordination proof.']};save(E/'programme-reconciliation.json',d);save(E/'remaining-work.json',remaining)
cols=['findingId','severity','candidateOnly','frozenDisposition','primaryPackage','localRepairStatus','fixAcceptance','target','release']
with (E/'programme-reconciliation.csv').open('w',newline='') as f:w=csv.DictWriter(f,fieldnames=cols);w.writeheader();w.writerows({k:r[k] for k in cols} for r in records)
text='# Remaining implementation and environment work\n\nLocal repair authorization remains valid. Missing external facts are not repeated approval requests.\n\n'
for r in remaining:text+='## '+r['taskId']+'\n\n'+r['minimumMaterialOrCondition']+'\n\n'
text+='## Target validation after local implementation\n\nQualified target Linux/filesystem+backup workers/snapshots, actual versions/systemd/proxy, client deployment catalog, supported browser/quota/queue/offline window, signed target budgets/observation/stop conditions, fully verified paired point+currentsecurity floor+safe oldartifact OR firstsafe maintenance. None has been fabricated; no deployment/production or real restore is authorized by this delivery.\n'
(E/'remaining-work.md').write_text(text)
print(implementation,validation,acceptance,'remaining',len(remaining))
