import { test, before, after } from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { createRequire } from 'node:module';
import bcrypt from 'bcryptjs';
import { PrismaClient } from '@prisma/client';
import { createApp } from '../../dist/bootstrap/createApp.js';
import { setRealSyncPermissions, syncV1Request, readSyncResult } from '../helpers/syncV1Fixture.mjs';
const url = new URL(process.env.DATABASE_URL);
assert.equal(url.hostname, '127.0.0.1');
assert.equal(url.pathname.slice(1), process.env.RDPMS_EXEC_OWNED_DB);
const db = new PrismaClient(), app = createApp({ db }), uuid = () => crypto.randomUUID(), trace = [];
let actor, token, builder;
const grants = ['projects.view', 'projects.update', 'projects.manage_members', 'tasks.view', 'tasks.create', 'tasks.update', 'tasks.delete', 'tasks.change_status', 'tasks.assign', 'milestones.view', 'milestones.create', 'milestones.update', 'milestones.delete', 'project_phases.view'];
async function fixture() { const p = await db.project.create({ data: { code: 'DELTA-' + uuid(), name: 'Owned original project', type: 'TESTING', managerId: actor.id, createdById: actor.id, members: { create: { userId: actor.id, role: 'OWNER' } } } }); const phase = await db.projectPhase.create({ data: { projectId: p.id, code: 'P1', name: 'Original phase', sortOrder: 1 } }), a = await db.task.create({ data: { projectId: p.id, title: 'Original A', phaseId: phase.id, createdById: actor.id } }), b = await db.task.create({ data: { projectId: p.id, title: 'Original B', createdById: actor.id } }), m = await db.milestone.create({ data: { projectId: p.id, name: 'Original milestone', dueDate: new Date('2026-10-10') } }); const file = await db.fileObject.create({ data: { storageKey: 'owned-no-bytes-' + uuid(), originalName: 'synthetic metadata only', mimeType: 'text/plain', sizeBytes: 0, accessScope: 'PROJECT', ownerProjectId: p.id, ownerUserId: actor.id } }); await db.attachment.create({ data: { fileId: file.id, entityType: 'TASK', entityId: a.id } }); await db.taskDependency.create({ data: { taskId: b.id, prerequisiteId: a.id } }); return { p, a, b, m, phase, file }; }
async function state(f) { return { project: await db.project.findUnique({ where: { id: f.p.id } }), tasks: await db.task.findMany({ where: { projectId: f.p.id }, orderBy: { id: 'asc' } }), milestones: await db.milestone.findMany({ where: { projectId: f.p.id }, orderBy: { id: 'asc' } }), attachments: await db.attachment.findMany({ where: { fileId: f.file.id } }), dependencies: await db.taskDependency.findMany({ where: { OR: [{ taskId: { in: [f.a.id, f.b.id] } }, { prerequisiteId: { in: [f.a.id, f.b.id] } }] } }), audits: await db.auditLog.findMany({ where: { entityId: f.p.id }, orderBy: { createdAt: 'asc' } }) }; }
async function request(endpoint, method = 'PUT', body, server = app) { const r = await server.request('/api' + endpoint, { method, headers: { Authorization: 'Bearer ' + token, 'Content-Type': 'application/json' }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) }); const v = await r.json(); trace.push({ endpoint, method, body, status: r.status, response: v }); return { r, v }; }
function fault() { return createApp({ db: new Proxy(db, { get(t, k) { if (k === '$transaction')
            return (fn, opts) => t.$transaction(tx => fn(new Proxy(tx, { get(t, k) { if (k === 'auditLog')
                    return new Proxy(t[k], { get(m, k) { if (k === 'create')
                            return async () => { throw Error('OWNED_CHILD_AUDIT_FAULT'); }; return typeof m[k] === 'function' ? m[k].bind(m) : m[k]; } }); return typeof t[k] === 'function' ? t[k].bind(t) : t[k]; } })), opts); return typeof t[k] === 'function' ? t[k].bind(t) : t[k]; } }) }); }
before(async () => { actor = await db.user.create({ data: { username: 'rp05delta-' + uuid(), displayName: 'Synthetic delta owner', systemRole: 'MEMBER', status: 'ACTIVE', passwordHash: await bcrypt.hash('Owned child fixture 2026!', 4) } }); await setRealSyncPermissions(db, actor.id, grants); const login = await app.request('/api/auth/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ username: actor.username, password: 'Owned child fixture 2026!' }) }); assert.equal(login.status, 200); const v = await login.json(); assert.equal(v.user.id, actor.id); token = v.accessToken; const req = createRequire(path.resolve('../frontend/package.json')); const esbuild = req('esbuild'); const module = path.join(process.env.RDPMS_EXEC_EVIDENCE_DIR, 'project-edit-command.mjs'); await esbuild.build({ entryPoints: [path.resolve('../frontend/src/shared/projectEditCommand.ts')], bundle: true, format: 'esm', platform: 'node', outfile: module }); builder = (await import(pathToFileURL(module).href)).buildProjectChildEdit; await esbuild.build({ entryPoints: [path.resolve('../frontend/src/components/EditProjectModal.tsx')], bundle: true, format: 'esm', platform: 'browser', outfile: path.join(process.env.RDPMS_EXEC_EVIDENCE_DIR, 'edit-modal-bundle.js'), tsconfig: path.resolve('../frontend/tsconfig.app.json') }); });
after(async () => { try {
    fs.writeFileSync(path.join(process.env.RDPMS_EXEC_EVIDENCE_DIR, 'persistent-state.json'), JSON.stringify({ trace, projects: await db.project.findMany(), tasks: await db.task.findMany(), milestones: await db.milestone.findMany(), attachments: await db.attachment.findMany(), dependencies: await db.taskDependency.findMany(), receipts: await db.syncMutation.findMany(), audits: await db.auditLog.findMany() }, null, 2));
}
finally {
    await db.$disconnect();
} });
test('actual candidate serializer and native JWT command preserve original child IDs/attachment/dependency and only change explicit fields', async () => { const f = await fixture(), original = JSON.parse(JSON.stringify(await state(f))); const before = await state(f); const body = builder({ updatedAt: original.project.updatedAt, tasks: original.tasks, milestones: original.milestones }, original.tasks.map(t => ({ ...t, title: t.id === f.a.id ? 'Edited A' : t.title })), original.milestones); assert.equal(body.tasks.length, 1); assert.deepEqual(body.deletedTaskIds, []); assert.equal((await request('/projects/' + f.p.id, 'PUT', body)).r.status, 200); const now = await state(f); assert.equal(now.tasks.length, 2); assert.equal(now.tasks.find(t => t.id === f.a.id).title, 'Edited A'); assert.deepEqual(now.tasks.find(t => t.id === f.b.id), before.tasks.find(t => t.id === f.b.id)); assert.deepEqual(now.attachments, before.attachments); assert.deepEqual(now.dependencies, before.dependencies); assert.deepEqual(now.milestones, before.milestones); });
test('legacy empty/omitted arrays preserve originals even without delete grant; explicit deletion denied without side effects', async () => { const f = await fixture(); await setRealSyncPermissions(db, actor.id, grants.filter(x => x !== 'tasks.delete')); for (const body of [{ name: 'safe legacy edit', tasks: [] }, { name: 'safe omission' }]) {
    assert.equal((await request('/projects/' + f.p.id, 'PUT', body)).r.status, 200);
    assert.equal(await db.task.count({ where: { projectId: f.p.id, deletedAt: null } }), 2);
} const before = await state(f); const r = await request('/projects/' + f.p.id, 'PUT', { baseUpdatedAt: before.project.updatedAt.toISOString(), deletedTaskIds: [f.b.id] }); assert.equal(r.r.status, 403); assert.deepEqual(await state(f), before); await setRealSyncPermissions(db, actor.id, grants); });
test('new task/milestone upserts succeed while stale/missing project/child baseline and unknown/cross IDs reject transaction', async () => { const f = await fixture(), outside = await fixture(); for (const body of [{ tasks: [{ title: 'missing project base' }] }, { baseUpdatedAt: '2000-01-01', tasks: [{ title: 'stale' }] }, { baseUpdatedAt: f.p.updatedAt.toISOString(), tasks: [{ id: f.a.id, title: 'missing child base' }] }, { baseUpdatedAt: f.p.updatedAt.toISOString(), tasks: [{ id: outside.a.id, baseUpdatedAt: outside.a.updatedAt.toISOString(), title: 'cross' }] }, { baseUpdatedAt: f.p.updatedAt.toISOString(), tasks: [{ id: uuid(), baseUpdatedAt: f.a.updatedAt.toISOString(), title: 'unknown' }] }]) {
    const before = await state(f), r = await request('/projects/' + f.p.id, 'PUT', body);
    assert.ok([400, 409].includes(r.r.status));
    assert.deepEqual(await state(f), before);
} assert.equal((await request('/projects/' + f.p.id, 'PUT', { baseUpdatedAt: f.p.updatedAt.toISOString(), tasks: [{ title: 'New legal task', phaseId: f.phase.id }], milestones: [{ name: 'New legal milestone', dueDate: '2026-10-12' }] })).r.status, 200); assert.equal(await db.task.count({ where: { projectId: f.p.id } }), 3); assert.equal(await db.milestone.count({ where: { projectId: f.p.id } }), 2); });
test('scalar/enumeration/forbidden fields fail clearly and strict audit fault rolls back child and parent state', async () => { const f = await fixture(); for (const payload of [{ title: {} }, { title: 'bad status', status: {} }, { title: 'bad priority', priority: 'BAD' }, { title: 'bad date', dueDate: 12 }, { title: 'system inject', code: 'SERVER-CODE' }, { title: 'bad phase', phaseId: [] }]) {
    const before = await state(f), r = await request('/projects/' + f.p.id, 'PUT', { baseUpdatedAt: f.p.updatedAt.toISOString(), tasks: [payload] });
    assert.equal(r.r.status, 400);
    assert.deepEqual(await state(f), before);
} const before = await state(f); assert.equal((await request('/projects/' + f.p.id, 'PUT', { baseUpdatedAt: f.p.updatedAt.toISOString(), name: 'must roll back', tasks: [{ id: f.a.id, baseUpdatedAt: f.a.updatedAt.toISOString(), title: 'must roll back' }] }, fault())).r.status, 500); assert.deepEqual(await state(f), before); });
test('explicit allowed tombstones are bounded, preserve attachment/dependency rows and appear in sync downlink', async () => { const f = await fixture(), before = await state(f); const denied = await request('/projects/' + f.p.id, 'PUT', { baseUpdatedAt: f.p.updatedAt.toISOString(), deletedTaskIds: [f.a.id] }); assert.equal(denied.r.status, 409); assert.deepEqual(await state(f), before); assert.equal((await request('/projects/' + f.p.id, 'PUT', { baseUpdatedAt: f.p.updatedAt.toISOString(), deletedTaskIds: [f.a.id, f.b.id], deletedMilestoneIds: [f.m.id] })).r.status, 200); const s = await state(f); assert.ok(s.tasks.every(t => t.deletedAt)); assert.ok(s.milestones[0].deletedAt); assert.deepEqual(s.attachments, before.attachments); assert.deepEqual(s.dependencies, before.dependencies); const pull = await request('/sync/init', 'GET'); assert.equal(pull.r.status, 200); for (const id of [f.a.id, f.b.id, f.m.id])
    assert.ok(JSON.stringify(pull.v).includes(id)); });
test('HTTP delete refuses anomalous cross-project child and keeps both projects; repeat owned leaf deletion stable noop', async () => { const f = await fixture(), other = await fixture(); await db.task.update({ where: { id: other.b.id }, data: { parentId: f.b.id } }); const before = await state(f), otherBefore = await state(other); assert.equal((await request('/tasks/' + f.b.id, 'DELETE')).r.status, 409); assert.deepEqual(await state(f), before); assert.deepEqual(await state(other), otherBefore); await db.task.update({ where: { id: other.b.id }, data: { parentId: null } }); assert.equal((await request('/tasks/' + f.b.id, 'DELETE')).r.status, 200); const tomb = await db.task.findUnique({ where: { id: f.b.id } }); const again = await request('/tasks/' + f.b.id, 'DELETE'); assert.equal(again.r.status, 200); assert.equal(again.v.noop, true); assert.equal((await db.task.findUnique({ where: { id: f.b.id } })).deletedAt.getTime(), tomb.deletedAt.getTime()); });
test('original bound v1 task delete still deliberately delete-wins/replays once and forbids external child cascade', async () => { const f = await fixture(); const body = { deviceId: 'delta-device-' + uuid(), changes: [{ clientMutationId: uuid(), entity: 'tasks', id: f.b.id, projectId: f.p.id, op: 'delete', baseUpdatedAt: '2000-01-01', data: {} }] }; const opts = { method: 'POST', headers: { Authorization: 'Bearer ' + token, 'Content-Type': 'application/json' }, body: JSON.stringify(body) }; const first = await syncV1Request(app, '/api/sync/push', opts, f.p.id); assert.equal(first.status, 200); assert.equal((await first.json()).results[0].status, 'applied'); const before = await db.task.findUnique({ where: { id: f.b.id } }); const auditBefore = await db.auditLog.count({ where: { entityId: f.b.id } }); const replay = await syncV1Request(app, '/api/sync/push', opts, f.p.id); assert.equal(replay.status, 200); assert.equal((await replay.json()).results[0].replayed, true); assert.equal((await db.task.findUnique({ where: { id: f.b.id } })).deletedAt.getTime(), before.deletedAt.getTime()); assert.equal(await db.auditLog.count({ where: { entityId: f.b.id } }), auditBefore); });
test('newly bound parent/phase must be live for ordinary task and sync; no DAG policy is activated', async () => { const f = await fixture(); await db.task.update({ where: { id: f.a.id }, data: { deletedAt: new Date() } }); await db.projectPhase.update({ where: { id: f.phase.id }, data: { deletedAt: new Date() } }); for (const patch of [{ parentId: f.a.id }, { phaseId: f.phase.id }]) {
    const before = await state(f);
    assert.equal((await request('/tasks/' + f.b.id, 'PUT', patch)).r.status, 400);
    const id = uuid(), body = { deviceId: 'live-ref-' + uuid(), changes: [{ clientMutationId: uuid(), entity: 'tasks', id, projectId: f.p.id, op: 'upsert', data: { title: 'denied new ref', ...patch } }] };
    const r = await syncV1Request(app, '/api/sync/push', { method: 'POST', headers: { Authorization: 'Bearer ' + token, 'Content-Type': 'application/json' }, body: JSON.stringify(body) }, f.p.id);
    const v = await readSyncResult(r);
    assert.equal(v.results[0].status, 'rejected');
    assert.equal(await db.task.findUnique({ where: { id } }), null);
    assert.deepEqual(await state(f), before);
} });
test('real delete-vs-new-child barrier rechecks live parent after row lock and preserves last safe state', async () => { const f = await fixture(); let deletionHit, releaseDelete, referenceHit; const reachedDelete = new Promise(r => deletionHit = r), deleteGate = new Promise(r => releaseDelete = r), reachedReference = new Promise(r => referenceHit = r); function proxy(mode) { return new Proxy(db, { get(t, k) { if (k === '$transaction')
        return (fn, opts) => t.$transaction(tx => fn(new Proxy(tx, { get(t, k) { if (mode === 'delete' && k === 'task')
                return new Proxy(t[k], { get(m, k) { if (k === 'findFirst')
                        return async (...args) => { deletionHit(); await deleteGate; return m.findFirst(...args); }; return typeof m[k] === 'function' ? m[k].bind(m) : m[k]; } }); if (mode === 'child' && k === '$queryRaw')
                return async (...args) => { if (String(args[0]).includes('FROM tasks'))
                    referenceHit(); return t.$queryRaw(...args); }; return typeof t[k] === 'function' ? t[k].bind(t) : t[k]; } })), opts); return typeof t[k] === 'function' ? t[k].bind(t) : t[k]; } }); } const deleting = request('/tasks/' + f.b.id, 'DELETE', undefined, createApp({ db: proxy('delete') })); let timer, child; try {
    await Promise.race([reachedDelete, new Promise((_, reject) => timer = setTimeout(() => reject(Error('delete row barrier not reached')), 5000))]);
    clearTimeout(timer);
    child = request('/tasks', 'POST', { projectId: f.p.id, parentId: f.b.id, title: 'late child cannot attach' }, createApp({ db: proxy('child') }));
    await Promise.race([reachedReference, new Promise((_, reject) => timer = setTimeout(() => reject(Error('native shared lock not reached')), 5000))]);
}
finally {
    clearTimeout(timer);
    releaseDelete();
} assert.equal((await deleting).r.status, 200); assert.equal((await child).r.status, 400); assert.equal(await db.task.count({ where: { projectId: f.p.id, title: 'late child cannot attach' } }), 0); assert.ok((await db.task.findUnique({ where: { id: f.b.id } })).deletedAt); });

test('prerequisite producer refuses tombstoned source/target and retains existing relations', async () => {
 const f = await fixture(); await db.task.update({where:{id:f.a.id},data:{deletedAt:new Date()}});
 const before = await state(f); const result = await request('/tasks/'+f.b.id+'/prerequisites','POST',{prerequisiteId:f.a.id});
 assert.ok([400,404].includes(result.r.status)); assert.deepEqual(await state(f),before);
});
