import { test, before, after } from 'node:test'; import assert from 'node:assert/strict'; import crypto from 'node:crypto'; import fs from 'node:fs'; import path from 'node:path'; import bcrypt from 'bcryptjs';
import { PrismaClient } from '@prisma/client'; import { createApp } from '../../dist/bootstrap/createApp.js';
const url=new URL(process.env.DATABASE_URL);assert.equal(url.hostname,'127.0.0.1');assert.equal(url.pathname.slice(1),process.env.RDPMS_EXEC_OWNED_DB);
const db=new PrismaClient();const app=createApp({db});const uuid=()=>crypto.randomUUID();let admin,actor,old,target,outsider,token;const trace=[];
async function user(kind,role='MEMBER'){return db.user.create({data:{username:'rp07-'+kind+'-'+uuid(),displayName:'Synthetic '+kind,passwordHash:await bcrypt.hash('Owned transfer fixture 2026!',4),systemRole:role,status:'ACTIVE'}})}
async function login(u){const r=await app.request('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:u.username,password:'Owned transfer fixture 2026!'})});assert.equal(r.status,200);const b=await r.json();assert.equal(b.user.id,u.id);return b.accessToken;}
async function fixture(subtype=null){return db.project.create({data:{code:'RP07-'+uuid(),name:'Owned transfer project',type:'TESTING',subtype,managerId:old.id,createdById:actor.id,members:{create:[{userId:actor.id,role:'OWNER'},{userId:old.id,role:'MANAGER'},{userId:target.id,role:'VIEWER'}]},...(subtype?{registrationProfile:{create:{}}}:{})}})}
async function call(endpoint,body,server=app,accessToken=token){const r=await server.request(endpoint,{method:'PUT',headers:{Authorization:'Bearer '+accessToken,'Content-Type':'application/json'},body:JSON.stringify(body)});const value=await r.json();trace.push({endpoint,body,status:r.status,response:value});return {r,value};}
async function state(p){return {project:await db.project.findUnique({where:{id:p.id}}),members:await db.projectMember.findMany({where:{projectId:p.id},orderBy:{userId:'asc'}}),audits:await db.auditLog.findMany({where:{entityId:p.id},orderBy:{createdAt:'asc'}})};}
async function syncTransfer(p,server=app){const change={clientMutationId:uuid(),entity:'projects',op:'upsert',id:p.id,projectId:p.id,baseUpdatedAt:p.updatedAt.toISOString(),data:{managerId:target.id}},device='rp07-device-'+uuid();const opts=changes=>({method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({protocolVersion:1,deviceId:device,changes})});const r=await server.request('/api/sync/receipts/reserve',opts([change]));assert.equal(r.status,200,JSON.stringify(await r.clone().json()));const b=await r.json();change.receiptHandle=b.results[0].receiptHandle;change.payloadHash=b.results[0].payloadHash;const push=await server.request('/api/sync/push',opts([change]));const outcome=await push.json();trace.push({endpoint:'sync',change,status:push.status,outcome});return {r:push,value:outcome,change,device};}
function fault(model,method){const proxy=new Proxy(db,{get(t,k){if(k==='$transaction')return(fn,opts)=>t.$transaction(tx=>fn(new Proxy(tx,{get(t,k){if(k===model)return new Proxy(t[k],{get(m,op){if(op===method)return async()=>{throw new Error('OWNED_TRANSFER_'+model+'_'+method)};const v=m[op];return typeof v==='function'?v.bind(m):v;}});const v=t[k];return typeof v==='function'?v.bind(t):v;}})),opts);const v=t[k];return typeof v==='function'?v.bind(t):v;}});return createApp({db:proxy});}
before(async()=>{admin=await user('admin','SUPER_ADMIN');actor=await user('owner');old=await user('old');target=await user('target');outsider=await user('outside');const grants=await db.permission.findMany({where:{code:{in:['projects.view','projects.update','projects.manage_members','registrations.update','registrations.view']}}});assert.equal(grants.length,5);const role=await db.role.create({data:{code:'rp07_'+uuid(),name:'Synthetic transfer grants',permissions:{create:grants.map(p=>({permissionId:p.id}))}}});await db.userRole.create({data:{userId:actor.id,roleId:role.id}});token=await login(actor);});
after(async()=>{try{fs.writeFileSync(path.join(process.env.RDPMS_EXEC_EVIDENCE_DIR,'persistent-state.json'),JSON.stringify({trace,projects:await db.project.findMany(),members:await db.projectMember.findMany(),receipts:await db.syncMutation.findMany(),audits:await db.auditLog.findMany()},null,2));}finally{await db.$disconnect();}});
test('HTTP/sync/registration same explicit transfer yields active targetMANAGER, priorMEMBER, OWNER retained and changed ACL',async()=>{for(const entry of ['http','sync','registration']){const p=await fixture(entry==='registration'?'registration':null);const before=await app.request('/api/sync/init',{headers:{Authorization:'Bearer '+token}});assert.equal(before.status,200);const oldAcl=(await before.json()).acl.aclVersion;const r=entry==='sync'?await syncTransfer(p):await call(`/api/${entry==='http'?'projects':'registrations'}/${p.id}`,{managerId:target.id,baseUpdatedAt:p.updatedAt.toISOString()});assert.equal(r.r.status,200,JSON.stringify(r.value));if(entry==='sync')assert.equal(r.value.results[0].status,'applied');const s=await state(p);assert.equal(s.project.managerId,target.id);assert.equal(s.members.find(x=>x.userId===target.id).role,'MANAGER');assert.equal(s.members.find(x=>x.userId===target.id).leftAt,null);assert.equal(s.members.find(x=>x.userId===old.id).role,'MEMBER');assert.equal(s.members.find(x=>x.userId===actor.id).role,'OWNER');assert.equal(s.audits.filter(x=>x.metadata?.command==='TRANSFER_MANAGER_V1').length,1);const after=await app.request('/api/sync/init',{headers:{Authorization:'Bearer '+token}});assert.notEqual((await after.json()).acl.aclVersion,oldAcl);}});
test('new OWNER keeps OWNER; old OWNER never automatically demoted',async()=>{const p=await fixture();await db.project.update({where:{id:p.id},data:{managerId:actor.id}});const current=await db.project.findUnique({where:{id:p.id}});const r=await call('/api/projects/'+p.id,{managerId:target.id,baseUpdatedAt:current.updatedAt.toISOString()});assert.equal(r.r.status,200);assert.equal((await state(p)).members.find(x=>x.userId===actor.id).role,'OWNER');const now=await db.project.findUnique({where:{id:p.id}});assert.equal((await call('/api/projects/'+p.id,{managerId:actor.id,baseUpdatedAt:now.updatedAt.toISOString()})).r.status,200);assert.equal((await state(p)).members.find(x=>x.userId===actor.id).role,'OWNER');});
test('missing/stale baseline, wrong scalar, absent/outside/left/disabled/deleted target have no business effects',async()=>{const p=await fixture();for(const body of [{managerId:target.id},{managerId:target.id,baseUpdatedAt:'2000-01-01'},{managerId:[]},{managerId:outsider.id,baseUpdatedAt:p.updatedAt.toISOString()},{managerId:uuid(),baseUpdatedAt:p.updatedAt.toISOString()}]){const before=await state(p);const r=await call('/api/projects/'+p.id,body);assert.ok([400,409].includes(r.r.status));assert.deepEqual(await state(p),before);}for(const kind of ['left','disabled','deleted']){if(kind==='left')await db.projectMember.update({where:{projectId_userId:{projectId:p.id,userId:target.id}},data:{leftAt:new Date()}});else await db.user.update({where:{id:target.id},data:kind==='disabled'?{status:'DISABLED'}:{deletedAt:new Date()}});const before=await state(p);const r=await call('/api/projects/'+p.id,{managerId:target.id,baseUpdatedAt:p.updatedAt.toISOString()});assert.equal(r.r.status,400);assert.deepEqual(await state(p),before);await db.projectMember.update({where:{projectId_userId:{projectId:p.id,userId:target.id}},data:{leftAt:null}});await db.user.update({where:{id:target.id},data:{status:'ACTIVE',deletedAt:null}});}});
test('current OWNER lacking manage_members and non-owner lacking capability cannot transfer or grant themselves management',async()=>{const p=await fixture();const access=await login(target);const before=await state(p);assert.equal((await call('/api/projects/'+p.id,{managerId:target.id,baseUpdatedAt:p.updatedAt.toISOString()},app,access)).r.status,403);const grants=await db.userRole.findMany({where:{userId:actor.id}});await db.userRole.deleteMany({where:{userId:actor.id}});try{assert.equal((await call('/api/projects/'+p.id,{managerId:target.id,baseUpdatedAt:p.updatedAt.toISOString()})).r.status,403);assert.deepEqual(await state(p),before);}finally{await db.userRole.createMany({data:grants});}});
for(const [model,method] of [['projectMember','update'],['projectMember','updateMany'],['project','update'],['auditLog','create']])test(`membership/project/strict audit fault ${model}.${method} rolls back whole transfer`,async()=>{const p=await fixture();const before=await state(p);const r=await call('/api/projects/'+p.id,{managerId:target.id,baseUpdatedAt:p.updatedAt.toISOString()},fault(model,method));assert.equal(r.r.status,500);assert.deepEqual(await state(p),before);});
test('same-base competing transfers have one success and preserve consistent manager/member outcome',async()=>{const p=await fixture();await db.projectMember.create({data:{projectId:p.id,userId:outsider.id,role:'MEMBER'}});const replies=await Promise.all([target,outsider].map(t=>call('/api/projects/'+p.id,{managerId:t.id,baseUpdatedAt:p.updatedAt.toISOString()})));assert.equal(replies.filter(r=>r.r.status===200).length,1);assert.ok(replies.some(r=>r.r.status===409));const s=await state(p);assert.equal(s.members.find(m=>m.userId===s.project.managerId).role,'MANAGER');assert.equal(s.members.find(m=>m.userId===old.id).role,'MEMBER');assert.equal(s.audits.filter(a=>a.metadata?.command==='TRANSFER_MANAGER_V1').length,1);});
test('unrelated generic edit does not silently reactivate historical left manager membership',async()=>{const p=await fixture();await db.projectMember.update({where:{projectId_userId:{projectId:p.id,userId:old.id}},data:{leftAt:new Date()}});const before=await db.projectMember.findUnique({where:{projectId_userId:{projectId:p.id,userId:old.id}}});assert.equal((await call('/api/projects/'+p.id,{name:'safe unrelated edit'})).r.status,200);assert.deepEqual(await db.projectMember.findUnique({where:{id:before.id}}),before);});

test('combined participant edit cannot undo owner/prior membership preservation of transfer',async()=>{const p=await fixture();const r=await call('/api/projects/'+p.id,{managerId:target.id,participantIds:[],baseUpdatedAt:p.updatedAt.toISOString()});assert.equal(r.r.status,200);const s=await state(p);for(const u of [actor,old,target])assert.equal(s.members.find(m=>m.userId===u.id).leftAt,null);assert.equal(s.members.find(m=>m.userId===actor.id).role,'OWNER');assert.equal(s.members.find(m=>m.userId===old.id).role,'MEMBER');assert.equal(s.members.find(m=>m.userId===target.id).role,'MANAGER');});

test('sync strict-audit failure retains pending receipt and rolls back manager and membership',async()=>{const p=await fixture();const before=await state(p);const r=await syncTransfer(p,fault('auditLog','create'));assert.equal(r.r.status,500);assert.deepEqual(await state(p),before);const receipt=await db.syncMutation.findUnique({where:{clientMutationId:r.change.clientMutationId}});assert.equal(receipt.status,'pending');});
test('current account admission is rechecked after JWT auth before transfer lock',async()=>{for(const who of [target,actor]){const p=await fixture();const before=await state(p);let reached,release;const hit=new Promise(r=>reached=r),gate=new Promise(r=>release=r);const proxy=new Proxy(db,{get(t,k){if(k==='$transaction')return(fn,opts)=>t.$transaction(tx=>fn(new Proxy(tx,{get(t,k){if(k==='$queryRaw')return async(...args)=>{if(String(args[0]).includes('FROM users')){reached();await gate;}return t.$queryRaw(...args);};const v=t[k];return typeof v==='function'?v.bind(t):v;}})),opts);const v=t[k];return typeof v==='function'?v.bind(t):v;}});const pending=call('/api/projects/'+p.id,{managerId:target.id,baseUpdatedAt:p.updatedAt.toISOString()},createApp({db:proxy}));try{await Promise.race([hit,new Promise((_,rej)=>setTimeout(()=>rej(new Error('manager lock not reached')),5000))]);await db.user.update({where:{id:who.id},data:{status:'DISABLED'}});}finally{release();}const r=await pending;assert.equal(r.r.status,who===actor?401:400);assert.deepEqual(await state(p),before);await db.user.update({where:{id:who.id},data:{status:'ACTIVE'}});}});
