import { test, before, after } from 'node:test';
import assert from 'node:assert/strict'; import crypto from 'node:crypto'; import fs from 'node:fs'; import path from 'node:path'; import bcrypt from 'bcryptjs';
import { PrismaClient } from '@prisma/client'; import { createApp } from '../../dist/bootstrap/createApp.js';
const url=new URL(process.env.DATABASE_URL);assert.equal(url.hostname,'127.0.0.1');assert.equal(url.pathname.slice(1),process.env.RDPMS_EXEC_OWNED_DB);
const db=new PrismaClient();const app=createApp({db});let member,manager,role,token,project,oldTask;
const trace=[];const uuid=()=>crypto.randomUUID();
async function pull(params={}){const r=await app.request('/api/sync/init?'+new URLSearchParams({paginationVersion:'1',...params}),{headers:{Authorization:'Bearer '+token}});const body=await r.json();trace.push({params,status:r.status,body});return {r,body};}
before(async()=>{
 const password='Owned ACL fixture 2026!'; manager=await db.user.create({data:{username:'rp08-manager-'+uuid(),displayName:'Synthetic manager',passwordHash:await bcrypt.hash(password,4),status:'ACTIVE',systemRole:'MEMBER'}});
 member=await db.user.create({data:{username:'rp08-member-'+uuid(),displayName:'Synthetic member',passwordHash:await bcrypt.hash(password,4),status:'ACTIVE',systemRole:'MEMBER'}});
 const permissions=await db.permission.findMany({where:{code:{in:['projects.view','tasks.view','tasks.update']}}});assert.equal(permissions.length,3);
 role=await db.role.create({data:{code:'rp08_'+uuid(),name:'Synthetic ACL grants',permissions:{create:permissions.map(p=>({permissionId:p.id}))}}});await db.userRole.create({data:{userId:member.id,roleId:role.id}});
 const login=await app.request('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:member.username,password})});assert.equal(login.status,200);const value=await login.json();assert.equal(value.user.id,member.id);token=value.accessToken;
 const me=await app.request('/api/auth/me',{headers:{Authorization:'Bearer '+token}});assert.equal(me.status,200);
 project=await db.project.create({data:{code:'RP08-'+uuid(),name:'Old historical authorized project',type:'TESTING',managerId:manager.id,createdById:manager.id,createdAt:new Date('2000-01-01'),updatedAt:new Date('2000-01-01')}});
 oldTask=await db.task.create({data:{projectId:project.id,title:'Historical last-copy task',createdById:manager.id,createdAt:new Date('2000-01-01'),updatedAt:new Date('2000-01-01')}});
});
after(async()=>{try{fs.writeFileSync(path.join(process.env.RDPMS_EXEC_EVIDENCE_DIR,'persistent-state.json'),JSON.stringify({trace,projects:await db.project.findMany(),members:await db.projectMember.findMany(),grants:await db.rolePermission.findMany({where:{roleId:role?.id}}),tasks:await db.task.findMany(),receipts:await db.syncMutation.findMany(),audits:await db.auditLog.findMany()},null,2));}finally{await db.$disconnect();}}); // Retain audit actors until owned whole database drop.
test('old cursor new membership receives historical project/tasks in current complete projection',async()=>{const before=await pull();assert.equal(before.r.status,200);assert.deepEqual(before.body.acl.projectIds,[]);await db.projectMember.create({data:{projectId:project.id,userId:member.id,role:'MEMBER'}});const after=await pull({since:before.body.cursor,aclVersion:before.body.acl.aclVersion});assert.equal(after.r.status,200);assert.equal(after.body.full,true);assert.ok(after.body.changes.projects.upserts.some(r=>r.id===project.id));assert.ok(after.body.changes.tasks.upserts.some(r=>r.id===oldTask.id));assert.notEqual(after.body.acl.aclVersion,before.body.acl.aclVersion);});
test('same project ids permissions but member role change changes fingerprint and explicit capabilities',async()=>{const before=await pull();await db.projectMember.update({where:{projectId_userId:{projectId:project.id,userId:member.id}},data:{role:'VIEWER'}});const after=await pull({since:before.body.cursor,aclVersion:before.body.acl.aclVersion});assert.deepEqual(after.body.acl.projectIds,before.body.acl.projectIds);assert.deepEqual(after.body.acl.permissions,before.body.acl.permissions);assert.notEqual(after.body.acl.aclVersion,before.body.acl.aclVersion);assert.deepEqual(after.body.acl.projects[0].capabilities,['read']);assert.equal(after.body.full,true);});
test('entity grant revoke in visible project returns no task projection and changed full ACL',async()=>{const before=await pull();assert.ok(before.body.changes.tasks.upserts.length);const permission=await db.permission.findUnique({where:{code:'tasks.view'}});await db.rolePermission.delete({where:{roleId_permissionId:{roleId:role.id,permissionId:permission.id}}});try{const after=await pull({since:before.body.cursor,aclVersion:before.body.acl.aclVersion});assert.equal(after.r.status,200);assert.deepEqual(after.body.acl.projectIds,before.body.acl.projectIds);assert.notEqual(after.body.acl.aclVersion,before.body.acl.aclVersion);assert.deepEqual(after.body.changes.tasks,{upserts:[],tombstones:[]});assert.ok(!after.body.acl.permissions.includes('tasks.view'));}finally{await db.rolePermission.create({data:{roleId:role.id,permissionId:permission.id}});}});
test('leave and rejoin preserve complete historical projection without replacing existing cursor by empty incremental',async()=>{const before=await pull();await db.projectMember.update({where:{projectId_userId:{projectId:project.id,userId:member.id}},data:{leftAt:new Date()}});const left=await pull({since:before.body.cursor,aclVersion:before.body.acl.aclVersion});assert.deepEqual(left.body.acl.projectIds,[]);assert.deepEqual(left.body.changes.tasks.upserts,[]);await db.projectMember.update({where:{projectId_userId:{projectId:project.id,userId:member.id}},data:{leftAt:null,joinedAt:new Date(),role:'MEMBER'}});const rejoined=await pull({since:left.body.cursor,aclVersion:left.body.acl.aclVersion});assert.equal(rejoined.body.full,true);assert.ok(rejoined.body.changes.tasks.upserts.some(r=>r.id===oldTask.id));});
test('every signed page rechecks current ACL: role change after first3000 rows prevents second-page data',async()=>{await db.task.createMany({data:Array.from({length:3000},(_,i)=>({id:'rp08-page-'+i+'-'+project.id,projectId:project.id,title:'Old page '+i,createdAt:new Date('2000-01-01'),updatedAt:new Date('2000-01-01')}))});const first=await pull({deviceId:'owned-rp08-page'});assert.equal(first.r.status,200);assert.equal(first.body.changes.tasks.upserts.length,3000);assert.equal(first.body.pagination.hasMore,true);const token=first.body.pagination.nextPageToken;await db.projectMember.update({where:{projectId_userId:{projectId:project.id,userId:member.id}},data:{role:'VIEWER'}});const next=await pull({deviceId:'owned-rp08-page',pageToken:token});assert.equal(next.r.status,409);assert.equal((next.body.error?.code??next.body.code),'SYNC_ACL_CHANGED');assert.equal(Object.hasOwn(next.body,'changes'),false);});
test('legacy timestamp always safely resnapshots; v2 signed committed checkpoint remains incremental',async()=>{let old=await pull();while(old.body.pagination.hasMore)old=await pull({pageToken:old.body.pagination.nextPageToken});const legacy=await pull({since:old.body.cursor,aclVersion:old.body.acl.aclVersion});assert.equal(legacy.r.status,200);assert.equal(legacy.body.full,true);assert.ok(legacy.body.changes.tasks.upserts.length);let v2=await pull({pullProtocol:'2',deviceId:'owned-v2-efficient'});while(v2.body.pagination.hasMore)v2=await pull({pullProtocol:'2',deviceId:'owned-v2-efficient',pageToken:v2.body.pagination.nextPageToken});const same=await pull({pullProtocol:'2',deviceId:'owned-v2-efficient',since:v2.body.cursor});assert.equal(same.r.status,200);assert.equal(same.body.full,false);assert.deepEqual(same.body.changes.tasks.upserts,[]);assert.equal(await db.syncMutation.count(),0);});
