import {test,before,after} from 'node:test';import assert from 'node:assert/strict';import crypto from 'node:crypto';import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import {spawn} from 'node:child_process';import {PrismaClient} from '@prisma/client';
const db=new PrismaClient(),url=new URL(process.env.DATABASE_URL);assert.equal(url.hostname,'127.0.0.1');assert.equal(url.pathname.slice(1),process.env.RDPMS_EXEC_OWNED_DB);const helper=path.resolve('../deploy/scripts/backup-pair.py');let root,env;const trace=[];
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
async function command(args,extra={}){let stdout='',stderr='';const p=spawn('python3',[helper,...args],{env:{...env,...extra}});p.stdout.on('data',b=>stdout+=b);p.stderr.on('data',b=>stderr+=b);const exit=await new Promise((resolve,reject)=>{p.on('error',reject);p.on('exit',resolve)});trace.push({args,runId:extra.RUN_ID,exit,stdout,stderr});return {exit,stdout,stderr,value:exit===0?JSON.parse(stdout):null};}
async function run(id,extra={}){const r=await command(['daily'],{RUN_ID:id,...extra});assert.equal(r.exit,0,r.stderr);return r.value;}
async function pair(id){return JSON.parse(await fs.readFile(path.join(root,'pg/pairs',id,'pair.json')));}
async function file(id,name){return fs.readFile(path.join(root,'uploads',id,name));}
before(async()=>{root=await fs.mkdtemp(path.join(os.tmpdir(),'rdpms-pair-owned-'));await fs.mkdir(path.join(root,'source'));await fs.writeFile(path.join(root,'source/a.txt'),'FIRST-IMMUTABLE');await fs.writeFile(path.join(root,'source/gone.txt'),'DELETE-ME');await db.project.create({data:{code:'OWNED-PAIR-'+crypto.randomUUID(),name:'Dump nonempty',type:'TESTING',manager:{create:{username:'pair-'+crypto.randomUUID(),displayName:'Owned pair actor',passwordHash:'synthetic-disabled',status:'DISABLED'}}}});env={...process.env,DB_NAME:process.env.RDPMS_EXEC_OWNED_DB,PGHOST:url.hostname,PGPORT:url.port,PGUSER:decodeURIComponent(url.username),PG_DIR:path.join(root,'pg'),UP_DIR:path.join(root,'uploads'),UPLOAD_SRC:path.join(root,'source')};});
after(async()=>{await db.$disconnect();const bytes=trace;await fs.rm(root,{recursive:true});await fs.writeFile(path.join(process.env.RDPMS_EXEC_EVIDENCE_DIR,'backup-pair-state.json'),JSON.stringify({trace:bytes,ownedRootRemoved:!(await fs.stat(root).catch(()=>null)),limits:['macOS owned filesystem, not targetLinux','Pair tags/hashes do not prove common DB/file live point; restoreEligible false']},null,2));});
test('two add/change/delete rounds retain first bytes and metadata, complete pair before latest and real dump readable',async()=>{const first=await run('fixed-timestamp-a');assert.equal(first.state,'PUBLISHED');assert.equal(await fs.readlink(path.join(root,'uploads/latest')),'fixed-timestamp-a');const m=await pair('fixed-timestamp-a');assert.equal(m.restoreEligible,false);const old=await file('fixed-timestamp-a','a.txt'),manifest=await file('fixed-timestamp-a','.rdpms-snapshot-manifest.json');await fs.writeFile(path.join(root,'source/a.txt'),'SECOND');await fs.unlink(path.join(root,'source/gone.txt'));await fs.writeFile(path.join(root,'source/new.txt'),'NEW');await run('fixed-timestamp-b');assert.deepEqual(await file('fixed-timestamp-a','a.txt'),old);assert.deepEqual(await file('fixed-timestamp-a','.rdpms-snapshot-manifest.json'),manifest);assert.equal((await file('fixed-timestamp-a','gone.txt')).toString(),'DELETE-ME');assert.equal((await file('fixed-timestamp-b','a.txt')).toString(),'SECOND');assert.equal((await file('fixed-timestamp-b','new.txt')).toString(),'NEW');assert.equal(await fs.stat(path.join(root,'uploads/fixed-timestamp-b/gone.txt')).catch(()=>null),null);assert.equal(await fs.readlink(path.join(root,'uploads/latest')),'fixed-timestamp-b');assert.ok((await fs.stat(path.join(root,'pg/pairs/fixed-timestamp-b/database.dump'))).size>1000);});
test('same run id completed verifies idempotently, different kind binding refuses and original pair untouched',async()=>{const before=await pair('fixed-timestamp-b');const again=await run('fixed-timestamp-b');assert.equal(again.state,'ALREADY_PUBLISHED');const conflict=await command(['weekly'],{RUN_ID:'fixed-timestamp-b'});assert.equal(conflict.exit,1);assert.match(conflict.stderr,/RUN_ID_BINDING_CONFLICT/);assert.deepEqual(await pair('fixed-timestamp-b'),before);});
test('unchanged files may share inode; metadata/content changes do not change any published predecessor',async()=>{await run('unchanged-c');const b=await fs.stat(path.join(root,'uploads/fixed-timestamp-b/new.txt')),c=await fs.stat(path.join(root,'uploads/unchanged-c/new.txt'));assert.equal(b.ino,c.ino);await fs.chmod(path.join(root,'source/new.txt'),0o640);await run('metadata-d');const after=await fs.stat(path.join(root,'uploads/metadata-d/new.txt'));assert.equal(after.mode&0o777,0o640);assert.equal((await fs.stat(path.join(root,'uploads/unchanged-c/new.txt'))).mode&0o777,b.mode&0o777);assert.notEqual(after.ino,b.ino);});
test('living OS run lease rejects backup/cleanup contender without source or latest change',async()=>{const hit=path.join(root,'lease-held');const p=spawn('python3',['-c','import fcntl,sys,pathlib;f=open(sys.argv[1],"a+");fcntl.flock(f,fcntl.LOCK_EX);pathlib.Path(sys.argv[2]).write_text("ready");sys.stdin.read()',path.join(root,'pg/pairs/.backup.lock'),hit]);try{for(let i=0;i<100&&!await fs.stat(hit).catch(()=>null);i++)await new Promise(r=>setTimeout(r,10));assert.ok(await fs.stat(hit));const latest=await fs.readlink(path.join(root,'uploads/latest'));const result=await command(['daily'],{RUN_ID:'lease-contender'});assert.equal(result.exit,1);assert.match(result.stderr,/BACKUP_RUN_BUSY/);assert.equal(await fs.readlink(path.join(root,'uploads/latest')),latest);assert.equal(await fs.stat(path.join(root,'pg/pairs/lease-contender')).catch(()=>null),null);}finally{p.stdin.end();await new Promise(r=>p.once('exit',r));}});
test('reserved manifest copy failure preserves old latest and cleans only own uncommitted stages',async()=>{const latest=await fs.readlink(path.join(root,'uploads/latest'));await fs.writeFile(path.join(root,'source/.rdpms-snapshot-manifest.json'),'user collision');const bad=await command(['daily'],{RUN_ID:'failed-copy'});assert.equal(bad.exit,1);assert.match(bad.stderr,/RESERVED_FILE_MANIFEST_COLLISION/);assert.equal(await fs.readlink(path.join(root,'uploads/latest')),latest);assert.deepEqual((await fs.readdir(path.join(root,'pg/pairs'))).filter(n=>n.startsWith('.staging-')),[]);assert.deepEqual((await fs.readdir(path.join(root,'uploads'))).filter(n=>n.startsWith('.staging-')),[]);await fs.unlink(path.join(root,'source/.rdpms-snapshot-manifest.json'));});
test('pair retention preserves last verified/latest/pinned/unknown and expires only complete matched pair',async()=>{const ids=['fixed-timestamp-a','fixed-timestamp-b','unchanged-c','metadata-d'];for(const id of ids){const p=path.join(root,'pg/pairs',id,'pair.json'),m=JSON.parse(await fs.readFile(p));m.createdAt='2000-01-0'+(ids.indexOf(id)+1)+'T00:00:00+00:00';if(id==='fixed-timestamp-a')m.restoreVerified=true;await fs.writeFile(p,JSON.stringify(m));}await fs.writeFile(path.join(root,'pg/pairs/fixed-timestamp-b/PINNED'),'fixture retention pin');await fs.mkdir(path.join(root,'uploads/legacy-unknown'));await fs.writeFile(path.join(root,'uploads/legacy-unknown/last-copy'),'KEEP');await run('retention-e',{KEEP_DAILY:'1'});assert.ok(await fs.stat(path.join(root,'pg/pairs/fixed-timestamp-a')));assert.ok(await fs.stat(path.join(root,'pg/pairs/fixed-timestamp-b')));assert.ok(await fs.stat(path.join(root,'uploads/legacy-unknown/last-copy')));assert.equal(await fs.stat(path.join(root,'pg/pairs/unchanged-c')).catch(()=>null),null);assert.equal(await fs.stat(path.join(root,'uploads/unchanged-c')).catch(()=>null),null);const invalid=await command(['daily'],{RUN_ID:'bad-retention',KEEP_DAILY:'-1'});assert.equal(invalid.exit,1);assert.equal(await fs.stat(path.join(root,'pg/pairs/bad-retention')).catch(()=>null),null);});
test('corrupt completed latest refuses link-dest and never overwrites files or claims success',async()=>{const latest=await fs.readlink(path.join(root,'uploads/latest')),p=path.join(root,'uploads',latest,'a.txt'),before=await fs.readFile(p);await fs.writeFile(p,'OWNED-CORRUPTION');const bad=await command(['daily'],{RUN_ID:'corruption-contender'});assert.equal(bad.exit,1);assert.match(bad.stderr,/PAIR_FILES_CHANGED/);assert.equal(await fs.readlink(path.join(root,'uploads/latest')),latest);await fs.writeFile(p,before); // This fixture intentionally damaged only owned current snapshot, not restore evidence.
});
