import {test,before,after} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import crypto from 'node:crypto';import {spawn} from 'node:child_process';
let root,plan,base,n=0;const commands=[];const helper=path.resolve('../deploy/scripts/drill/release-gates.py'),hash=x=>crypto.createHash('sha256').update(x).digest('hex');
async function save(p,d){await fs.writeFile(p,JSON.stringify(d));}
async function bound(name,data){await save(path.join(root,name),data);return{path:name,sha256:hash(await fs.readFile(path.join(root,name)))};}
async function run(mutator=()=>{},planMutator=()=>{}){const c=structuredClone(base);await mutator(c);const graph={tasks:[{id:'DTO',implementationDependencies:['PREP'],acceptanceDependencies:[],gateRequirements:[],activation:'STANDARD',acceptanceCaseIds:['DTO-OK'],contractRefs:[]},{id:'PREP',implementationDependencies:[],acceptanceDependencies:[],gateRequirements:[],activation:'STANDARD',acceptanceCaseIds:[],contractRefs:[]},{id:'TOKEN',implementationDependencies:[],acceptanceDependencies:[],gateRequirements:[{ref:'TOKEN-POLICY',before:'IMPLEMENTATION',condition:'always'}],activation:'STANDARD',acceptanceCaseIds:[],contractRefs:[]},{id:'OPTION',implementationDependencies:[],acceptanceDependencies:[],gateRequirements:[],activation:'OPTIONAL_IF_APPROVED',acceptanceCaseIds:[],contractRefs:[]}]};const state={tasks:Object.fromEntries(graph.tasks.map(t=>[t.id,{implementation:'COMPLETE',validation:'PASS'}]))};await planMutator(graph,state);await save(path.join(plan,'TASK_GRAPH.json'),graph);await save(path.join(plan,'IMPLEMENTATION_STATE.json'),state);const input=path.join(root,'input-'+(++n)+'.json'),output=path.join(root,'output-'+n+'.json');await save(input,c);let stdout='',stderr='';const p=spawn('python3',[helper,'--plan',plan,'--candidate',input,'--evidence',output]);p.stdout.on('data',b=>stdout+=b);p.stderr.on('data',b=>stderr+=b);const exit=await new Promise((r,j)=>{p.on('error',j);p.on('exit',r)});const value=JSON.parse(await fs.readFile(output));commands.push({case:n,exit,stdout,stderr,blockers:value.blockers});return value;}
before(async()=>{root=await fs.mkdtemp(path.join(os.tmpdir(),'rdpms-release-evaluator-owned-'));plan=path.join(root,'plan');await fs.mkdir(plan);await fs.writeFile(path.join(plan,'ACCEPTANCE_MATRIX.csv'),'case_id,result,evidence_ref\nDTO-OK,PASS,../case.json\n');await save(path.join(plan,'CROSS_PACKAGE_CONTRACTS.json'),{contracts:[]});await fs.writeFile(path.join(root,'source.js'),'owned fixture');const proof=await bound('case.json',{cases:[{caseId:'DTO-OK',result:'PASS'}]});const manifestRef=await bound('manifest.json',{state:'PREPARED_PRE_DDL',result:'PASS',criticalFailures:[],buildId:'owned-build',candidate:root,sourceBindings:{'source.js':hash(await fs.readFile(path.join(root,'source.js')))},buildBindings:{}});const baseSourceManifestRef=await bound('base-source.json',{sourceBindings:{'source.js':'0'.repeat(64)}});const target=await bound('target.json',{kind:'SIMULATED_DOCUMENT_CONTROL',note:'Only calculator fixture, not target proof'});base={repoRoot:root,candidateId:'owned-calculator-fixture',buildId:'owned-build',includedTaskIds:['DTO'],affectedTaskIds:[],manifestRef,baseSourceManifestRef,changedArtifactFiles:['source.js'],sourceOwners:{'source.js':['DTO']},caseEvidence:{'DTO-OK':{...proof,result:'PASS'}},rollback:{mode:'STOP_WRITES_AND_SERVICE',targetRunbookVerified:true,preserveRecoveryPoint:true,...target}};for(const field of ['supportedClientWindow','schemaCompatibility','environmentBudgets','observationWindow','stopThresholds','releaseOwner','qualifiedTargetApproval','verifiedRestorePoint'])base[field]={status:'VERIFIED',...target};});
after(async()=>{await fs.rm(root,{recursive:true});await fs.writeFile(path.join(process.env.RDPMS_EXEC_EVIDENCE_DIR,'release-evaluator-controls.json'),JSON.stringify({kind:'REAL_READ_ONLY_CALCULATOR_WITH_SYNTHETIC_PLAN_DOCUMENTS',commands,cleanup:{ownedRootRemoved:!(await fs.stat(root).catch(()=>null))},release:'NOT_EVALUATED'},null,2));});
test('scoped DTO includes transitive prep, excludes unrelated token and optional expansion, never approves release',async()=>{const v=await run();assert.deepEqual(v.implementationClosure,['DTO','PREP']);assert.equal(v.blockers.length,0);assert.equal(v.eligibleForTargetReview,true);assert.equal(v.release,'NOT_EVALUATED');});
test('incomplete implementation dependency blocks; acceptance dependency is evidence edge, not implementation closure',async()=>{let v=await run(()=>{},(g,s)=>{s.tasks.PREP.implementation='IN_PROGRESS'});assert.ok(v.blockers.some(b=>b.code==='IMPLEMENTATION_INCOMPLETE'));v=await run(()=>{},(g,s)=>{g.tasks[0].acceptanceDependencies=['TOKEN'];s.tasks.TOKEN.validation='NOT_RUN'});assert.equal(v.implementationClosure.includes('TOKEN'),false);assert.ok(v.blockers.some(b=>b.code==='ACCEPTANCE_DEPENDENCY_PENDING'));});
test('condition false is NOT_APPLICABLE; unknown condition blocks, not expanded into global package gate',async()=>{const alter=(g)=>{g.tasks[0].gateRequirements=[{ref:'CUSTOM-ROLES',before:'IMPLEMENTATION',condition:'custom binding activated'}]};let v=await run(c=>{c.conditionResults={'DTO:CUSTOM-ROLES':false}},alter);assert.equal(v.gates[0].result,'NOT_APPLICABLE');assert.equal(v.blockers.length,0);v=await run(()=>{},alter);assert.ok(v.blockers.some(b=>b.code==='GATE_CONDITION_UNKNOWN'));});
test('unbound success and unrelated acceptance file cannot substitute actual case proof',async()=>{let v=await run(c=>c.caseEvidence['DTO-OK'].sha256='0'.repeat(64));assert.ok(v.blockers.some(b=>b.code==='CASE_NOT_PASSED_OR_UNBOUND'));v=await run(c=>{c.caseEvidence['DTO-OK']={...base.rollback,result:'PASS'}});assert.ok(v.blockers.some(b=>b.code==='CASE_NOT_PASSED_OR_UNBOUND'));});
test('source/output drift and absent owner scope block independently',async()=>{const v=await run(c=>{c.sourceOwners['source.js']=['TOKEN'];c.buildId='wrong-build'});assert.ok(v.blockers.some(b=>b.code==='SOURCE_OWNER_SCOPE_UNCOVERED'));assert.ok(v.blockers.some(b=>b.code==='CANDIDATE_BUILD_ID_MISMATCH'));await fs.writeFile(path.join(root,'source.js'),'OWNED DRIFT');const drift=await run();assert.ok(drift.blockers.some(b=>b.code==='CANDIDATE_SOURCE_DRIFT'));await fs.writeFile(path.join(root,'source.js'),'owned fixture');});
test('missing target windows/budgets, scalar pretend approval, unsafe previous artifact deny release readiness',async()=>{const v=await run(c=>{c.supportedClientWindow='UNKNOWN';c.environmentBudgets=true;c.rollback={...base.rollback,mode:'SAFE_ARTIFACT',securityFloorSafe:false,schemaProtocolCompatible:true}});assert.ok(v.blockers.some(b=>b.field==='supportedClientWindow'));assert.ok(v.blockers.some(b=>b.field==='environmentBudgets'));assert.ok(v.blockers.some(b=>b.code==='UNSAFE_OR_UNBOUND_ROLLBACK'));});
test('explicit optional activation and contract applicability missing are recorded precisely',async()=>{const v=await run(c=>c.includedTaskIds.push('OPTION'),g=>g.tasks[0].contractRefs=['PC-SHARED']);assert.ok(v.blockers.some(b=>b.code==='OPTIONAL_TASK_NOT_ACTIVATED'));assert.ok(v.blockers.some(b=>b.code==='CONTRACT_APPLICABILITY_UNKNOWN'));});

test('claimed gate PASS backed by unrelated JSON is rejected; omitted source change inventory is detected',async()=>{const v=await run(c=>{c.gateEvidence={'S05-FAKE':{...base.rollback,result:'PASS',kind:'TARGET_RUNTIME',scopeTaskIds:['DTO']}};c.changedArtifactFiles=[]},g=>g.tasks[0].gateRequirements=[{ref:'S05-FAKE',before:'RELEASE',condition:'always'}]);assert.ok(v.blockers.some(b=>b.code==='GATE_EVIDENCE_REQUIRED'));assert.ok(v.blockers.some(b=>b.code==='SOURCE_CHANGE_INVENTORY_MISMATCH'));});

test('alias uses one approved scoped decision; merely affected task is not an approved scope',async()=>{await save(path.join(root,'approved-contract.json'),{scope:'Owned calculator fixture'});const ref=await bound('decision-register.json',{decisions:[{id:'D-S01-04',status:'APPROVED',approvedBy:'Owned hypothetical approver',approvedScope:['DTO'],affectedTaskIds:['DTO','PREP'],evidenceRef:'approved-contract.json'}]});const v=await run(c=>{c.gateEvidence={'D-S01-04':{...ref,kind:'LOCAL_DECISION',result:'PASS',scopeTaskIds:['DTO','PREP']}}},g=>{g.tasks[0].gateRequirements=[{ref:'S03-OI-06',before:'IMPLEMENTATION',condition:'same D-S01-04 approval'}];g.tasks[1].gateRequirements=[{ref:'D-S01-04',before:'IMPLEMENTATION',condition:'always'}]});const permitted=v.gates.find(g=>g.taskId==='DTO');assert.equal(permitted.result,'UNKNOWN');const v2=await run(c=>{c.conditionResults={'DTO:S03-OI-06':true};c.gateEvidence={'D-S01-04':{...ref,kind:'LOCAL_DECISION',result:'PASS',scopeTaskIds:['DTO','PREP']}}},g=>{g.tasks[0].gateRequirements=[{ref:'S03-OI-06',before:'IMPLEMENTATION',condition:'same D-S01-04 approval'}];g.tasks[1].gateRequirements=[{ref:'D-S01-04',before:'IMPLEMENTATION',condition:'always'}]});assert.equal(v2.gates.find(g=>g.taskId==='DTO').result,'PASS');assert.equal(v2.gates.find(g=>g.taskId==='PREP').result,'MISSING_OR_UNBOUND');});
